apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-order-query-db
spec:
  selector:
    matchLabels:
      app: mysql-order-query
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-order-query
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-order-query
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-query-db
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-query-db
        persistentVolumeClaim:
          claimName: mysql-pv-claim-order-query
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-order-query-db-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-order-query
